spring.application.name=inventario

# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/el_paisita_up
spring.datasource.username=postgres
spring.datasource.password=1805940

# Propiedad CRUCIAL para actualizar las columnas de IVA y Precios automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect