spring.application.name=inventario
spring.datasource.url=jdbc:postgresql://localhost:5432/el_paisita_up
spring.datasource.username=postgres
spring.datasource.password=1805940

# Esto hará que Spring cree las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true